# Generated by Django 5.2 on 2025-05-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varition_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varition_value',
            new_name='variation_value',
        ),
    ]
